//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSV_Entities : DbContext
    {
        public QLSV_Entities()
            : base("name=QLSV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<tblDiem> tblDiems { get; set; }
        public virtual DbSet<tblGiaoVien> tblGiaoViens { get; set; }
        public virtual DbSet<tblMonHoc> tblMonHocs { get; set; }
        public virtual DbSet<tblSinhVien> tblSinhViens { get; set; }
    }
}
